const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.video,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.Text,
		C3.Plugins.skymen_mask,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.video.Acts.Play,
		C3.Plugins.video.Acts.Pause,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.video.Cnds.IsPlaying,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.video.Cnds.IsOnLayer,
		C3.Plugins.video.Acts.SetPlaybackTime,
		C3.Plugins.video.Cnds.PickByUID,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.skymen_mask.Acts.SetWidth,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{Video1: 0},
	{posX: 0},
	{posY: 0},
	{Tween: 0},
	{menuBg: 0},
	{itemIndex: 0},
	{su: 0},
	{etilenGlikol: 0},
	{gliserin: 0},
	{Touch: 0},
	{refreshBtn: 0},
	{audioBtn: 0},
	{shareBtn: 0},
	{fullScreenBtn: 0},
	{Browser: 0},
	{loaderEmpty: 0},
	{loaderFill: 0},
	{loaderLogo: 0},
	{Video2: 0},
	{Video3: 0},
	{Sprite: 0},
	{Text: 0},
	{Sprite2: 0},
	{emptyGraph: 0},
	{fillGraph: 0},
	{maskAlt: 0},
	{maskUst: 0},
	{tablo: 0},
	{row: 0},
	{col: 0},
	{isShow: 0},
	{tableCell: 0},
	{val: 0},
	{engel: 0},
	{tabloBtn: 0},
	{grafikBtn: 0},
	{menuItems: 0},
	{videos: 0},
	{animStart: 0},
	{showKulpOutline: 0},
	{showMenuItemOutline: 0},
	{showDereceOutline: 0},
	{videoStart: 0},
	{videoUIDArray: 0},
	{videoTimeArray: 0},
	{activeItemIndex: 0},
	{activeLayer: 0},
	{timeCount: 0},
	{timeStart: 0},
	{isLoader: 0}
];

self.InstanceType = {
	Video1: class extends self.IWorldInstance {},
	menuBg: class extends self.ISpriteInstance {},
	su: class extends self.ISpriteInstance {},
	etilenGlikol: class extends self.ISpriteInstance {},
	gliserin: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	refreshBtn: class extends self.ISpriteInstance {},
	audioBtn: class extends self.ISpriteInstance {},
	shareBtn: class extends self.ISpriteInstance {},
	fullScreenBtn: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	loaderEmpty: class extends self.ISpriteInstance {},
	loaderFill: class extends self.ISpriteInstance {},
	loaderLogo: class extends self.ISpriteInstance {},
	Video2: class extends self.IWorldInstance {},
	Video3: class extends self.IWorldInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	emptyGraph: class extends self.ISpriteInstance {},
	fillGraph: class extends self.ISpriteInstance {},
	maskAlt: class extends self.IWorldInstance {},
	maskUst: class extends self.IWorldInstance {},
	tablo: class extends self.ISpriteInstance {},
	tableCell: class extends self.ISpriteInstance {},
	engel: class extends self.ISpriteInstance {},
	tabloBtn: class extends self.ISpriteInstance {},
	grafikBtn: class extends self.ISpriteInstance {},
	menuItems: class extends self.ISpriteInstance {},
	videos: class extends self.IWorldInstance {}
}